For this homework assignment, you are to submit a **single** ipynb file. Use the provided ipynb file to keep the same formatting for each question. In the ipynb file name, replace "NAME" with your first name. Unless otherwise specified, present your code as well as the output in your report. It is the student's responsibility to make sure the ipynb file runs when submitted. This assignment is worth 45 points.

# 1: Vectors *(20 Points)*

In Python, vectors are simply arrays from the NumPy package (usually loaded as np). Load the NumPy package and create a vector of size 6 with zero elements, positive elements, negative elements, and fractional elements. Call this vector x. *(2 points)*

In [ ]:
import numpy as np

In [ ]:
x = np.array((6,0,7,-9,2/3,4))
print(x)

[ 6.          0.          7.         -9.          0.66666667  4.        ]


Run the following commands and explain what each one does. *(3 points)*

In [ ]:
print(x.size)
print(x[3])
print(x[-1])

6
-9.0
4.0


The first line of code prints the size of the vector, showing that the vector contains 6 elements. The second line of code returns the 3rd element in the vector starting at 0, therby returning -9. The third line of code returns the last element of the vector by counting in reverse, thereby starting with the last element of the vector when using -1.

In order to do exponents in Python, we use the command `**`. In other words, $2^3$ is represented by `2**3`.

Write a function that computes the Euclidean norm of a vector of arbitrary size. Then use your function to find the magnitude of x. *(5 points)*



In [ ]:
def enorm(v):
  mid2=0
  for i in v:
    mid = i**2
    mid2=mid2+mid
  normed=np.sqrt(mid2)
  return print(normed)

enorm(x)

13.50719972623654


Now, import the `linalg` directory inside NumPy and use the `norm` function to verify that your handmade function worked! *(2 points)*

In [ ]:
import numpy.linalg as lin
lin.norm(x)

13.50719972623654

For vector addition and scalar multiplication, it works how you hope it would with `+` and `*`. Find a unit vector in the same direction of x through scalar multiplication and then add it to the vector $y=\begin{pmatrix}
1 \\ 3 \\ 5 \\ -3 \\ 0 \\ 2 \end{pmatrix}$. *(3 points)*

In [ ]:
y = np.array((1,2,5,-3,0,2))
u = 1/lin.norm(x)
print((x*u) + y)

[ 1.44420754  2.          5.51824213 -3.66631131  0.04935639  2.29613836]


Write a function that calculates the dot product between two vectors. Then use that to find the dot product of x and y. *(5 points)*

In [ ]:
def dots(numf,numd):
  tot=0
  for i in range(np.size(numf)):
    lol=numf[i]*numd[i]
    tot=tot+lol
  return tot
dots(x,y)

76.0

NumPy has two built-in functions for finding the dot product!

In [ ]:
print(np.dot(x,y))
print(x.dot(y))

76.0
76.0
[ 6.          0.          7.         -9.          0.66666667  4.        ]
[ 1  2  5 -3  0  2]


# 2: Matrices *(20 Points)*

A matrix is an array of arrays. Make an array using x and y as the elements of the array. Call this object M. *(2 points)*

In [ ]:
M=np.array((x,y))
print(M)

[[ 6.          0.          7.         -9.          0.66666667  4.        ]
 [ 1.          2.          5.         -3.          0.          2.        ]]


Explain the difference between the size and shape of M. The dimensions of a matrix are always represented as (rows) $\times$ (columns) *(2 points)*

In [ ]:
print(M.size)
print(M.shape)

12
(2, 6)


The differences between size and shape is that size is returning the total number of elements in the matrix (12) while shape returns the number of rows by the number of columns in the matrix (2,6).

Given a matrix M, there is another special and very useful matrix associated to it, called the transpose of M. We can find the transpose by using the `T` function from NumPy. Find the transpose of M and after looking at the transpose, explain what you think the transpose is. *(2 points)*

In [ ]:
tr=np.transpose(M)
print(tr)

[[ 6.          1.        ]
 [ 0.          2.        ]
 [ 7.          5.        ]
 [-9.         -3.        ]
 [ 0.66666667  0.        ]
 [ 4.          2.        ]]


I believe transpose is inverting the columns and rows of the matrix, where the first row becomes the first column and the second row becomes the second column.

Run the following code constructing a matrix as a list of lists. Then add M and N together using the regular addition symbol! *(2 points)*

In [ ]:
N=[[1,2,3,4,5,6],[0,-1,-2,-3,4,5]]
N=np.array(N)
O=M+N
print(O)

[[ 7.          2.         10.         -5.          5.66666667 10.        ]
 [ 1.          1.          3.         -6.          4.          7.        ]]


To find the element in the $M_{i+1,j+1}$, we will want to use the command `M[i,j]`. Have Python print the element $M_{1,4}$.

The `:` command inside the brackets, `[]` allow us to return an entire array. Play around with commands similar to `M[i,j]` to call the first row of M and the second column of N. *(3 points)*

In [ ]:
print(M[1,4])
print(M[0:1])
print(N[:,1:2])

0.0
[[ 6.          0.          7.         -9.          0.66666667  4.        ]]
[[ 2]
 [-1]]


Is matrix multiplication done with `*`? If it is possible to multiply M and N together, then try it with `*`. *(0.5 points)*

In [ ]:
print(M*N)
M*(N.T) # can't use *

[[  6.           0.          21.         -36.           3.33333333
   24.        ]
 [  0.          -2.         -10.           9.           0.
   10.        ]]


ValueError: operands could not be broadcast together with shapes (2,6) (6,2) 

You should understand why this isn't the correct matrix multiplication. This is elementwise multiplication. Write a function that will compute matrix multiplication on two matrices P (size m x n) and Q (size n x r). *(6 points)*

Hint: You will need to have Python record the dimensions of both P and Q and then either build the matrix by building arrays, or build a zero matrix and update the entries one at a time.

*Your function should utilize an earlier function you created instead of a built-in function.*

In [ ]:
def matmult(P,Q):
  (r,c)=P.shape
  (k,l)=Q.shape
  mat=np.zeros((r,l))
  for i in range(r):
    for w in range(l):
      mat[i,w]=dots(P[i,:],Q[:,w])
  return mat

If you try and plug M and N into your function, it will not work (look at the dimensions). Is there an operation you can do to N so that you get a new matrix T that you could do the matrix multiplication of with M? *(2 points)*

Hint: Look at earlier parts!

In [ ]:
op=N.T #transpose the N matrix or the M matrix
ne=M.T

Verify that your function works by computing the prebuilt function dot (similar to what we did with vectors). *(0.5 points)*

In [ ]:
print(matmult(M,op))
print(matmult(ne,N))

[[18.33333333 35.66666667]
 [20.          7.        ]]
[[  6.          11.          16.          21.          34.
   41.        ]
 [  0.          -2.          -4.          -6.           8.
   10.        ]
 [  7.           9.          11.          13.          55.
   67.        ]
 [ -9.         -15.         -21.         -27.         -57.
  -69.        ]
 [  0.66666667   1.33333333   2.           2.66666667   3.33333333
    4.        ]
 [  4.           6.           8.          10.          28.
   34.        ]]


# 3: Arrays *(5 Points)*

There are a few special arrays that are often made adn so have functions to make them: an array of all zeroes, an array of all ones, and an empty array. The `zeros`, `eye`, and `empty` functions create the desired array.

In [ ]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

Write a script of code that constructs a matrix where the number of rows is a random number between 4 and 8 and the code asks the user for the number of columns of the matrix (between 2 and 9).

The line of code should create 2 matrices, one where every other row is all ones and one where every other columns is all ones. The rest of the elements should be zero. The result should return the sum of these two matrices. *(5 points)*

In [ ]:
import random as rand

def numb(ws):
  if ws>=2 and ws<=9:
    rander=rand.randint(4,8)
    mtz=np.zeros((rander,ws))
    mta=np.zeros((rander,ws))
    (bp,zw)=mtz.shape
    tal=1
    tad=1
    for i in range(0,bp,2):
      mtz[i,:]=1
    for w in range(0,zw,2):
      mta[:,w]=1
    maltz=mtz+mta
  else:
    maltz="Incompatable answer"
  return maltz

ind = int(input("choose a number between 2 and 9: "))

print(numb(ind))

choose a number between 2 and 9: 9
[[2. 1. 2. 1. 2. 1. 2. 1. 2.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [2. 1. 2. 1. 2. 1. 2. 1. 2.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [2. 1. 2. 1. 2. 1. 2. 1. 2.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [2. 1. 2. 1. 2. 1. 2. 1. 2.]]
